import { env } from 'cloudflare:workers';
import type {Catalogue,Product,Category,Market,Settings} from './model';
import {demoProducts,seedCategories,defaultSettings} from './seed';
export function database():D1Database {const db=(env as unknown as {DB:D1Database}).DB;if(!db)throw new Error('Database unavailable');return db;}
export function bucket():R2Bucket {const b=(env as unknown as {MEDIA:R2Bucket}).MEDIA;if(!b)throw new Error('Media storage unavailable');return b;}
export async function seed(){const db=database();const marker=await db.prepare('SELECT id FROM site_settings WHERE id = ?').bind('main').first();if(marker)return;await db.batch([...seedCategories.map(c=>db.prepare('INSERT OR IGNORE INTO categories (id,name,image,icon,position,hidden) VALUES (?,?,?,?,?,?)').bind(c.id,c.name,c.image,c.icon,c.position,0)),...demoProducts.map(p=>db.prepare('INSERT OR IGNORE INTO products (id,slug,name,category_id,price,published,archived,data,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.slug,p.name,p.categoryId,p.price,1,0,JSON.stringify(p),p.createdAt,p.updatedAt)),db.prepare('INSERT OR IGNORE INTO site_settings (id,data) VALUES (?,?)').bind('main',JSON.stringify(defaultSettings))]);}
export async function catalogue(admin=false):Promise<Catalogue>{await seed();const db=database();const [ps,cs,ms,ims,cols,mp,md,s]=await Promise.all([db.prepare('SELECT * FROM products'+(admin?'':' WHERE published=1 AND archived=0')).all<any>(),db.prepare('SELECT * FROM categories ORDER BY position').all<any>(),db.prepare('SELECT * FROM markets').all<any>(),db.prepare('SELECT * FROM product_images ORDER BY position').all<any>(),db.prepare('SELECT * FROM product_colours').all<any>(),db.prepare('SELECT * FROM market_products').all<any>(),db.prepare('SELECT * FROM market_deals').all<any>(),db.prepare('SELECT data FROM site_settings WHERE id=?').bind('main').first<any>()]);const categories=cs.results.map(c=>({...c,hidden:!!c.hidden}));return {products:ps.results.map(row=>{const p:Product=JSON.parse(row.data);return {...p,price:row.price,published:!!row.published,archived:!!row.archived,photos:ims.results.filter(i=>i.product_id===p.id).map(i=>({id:i.id,mediaId:i.media_id,url:i.url,alt:i.alt})),colours:cols.results.some(c=>c.product_id===p.id)?cols.results.filter(c=>c.product_id===p.id).map(c=>({name:c.name,hex:c.hex,photo:c.photo})):p.colours};}).filter(p=>admin||categories.some(c=>c.id===p.categoryId&&!c.hidden)),categories:categories.filter(c=>admin||!c.hidden),markets:ms.results.map(row=>({...JSON.parse(row.data),products:mp.results.filter(r=>r.market_id===row.id).map(r=>r.product_id),deals:md.results.filter(r=>r.market_id===row.id).map(r=>r.label)})).filter(m=>admin||m.status!=='Pending'),settings:{...defaultSettings,...JSON.parse(s.data)}};}
export async function saveProduct(p:Product){const db=database();const now=new Date().toISOString();p.updatedAt=now;p.createdAt=p.createdAt||now;await db.batch([db.prepare('INSERT INTO products (id,slug,name,category_id,price,published,archived,data,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,name=excluded.name,category_id=excluded.category_id,price=excluded.price,published=excluded.published,archived=excluded.archived,data=excluded.data,updated_at=excluded.updated_at').bind(p.id,p.slug,p.name,p.categoryId,p.price,+p.published,+p.archived,JSON.stringify({...p,photos:[],colours:[]}),p.createdAt,now),db.prepare('DELETE FROM product_images WHERE product_id=?').bind(p.id),db.prepare('DELETE FROM product_colours WHERE product_id=?').bind(p.id),...p.photos.map((im,i)=>db.prepare('INSERT INTO product_images (id,product_id,media_id,url,alt,position) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),p.id,im.mediaId||null,im.url,im.alt,i)),...p.colours.map(c=>db.prepare('INSERT INTO product_colours (id,product_id,name,hex,photo) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),p.id,c.name,c.hex,c.photo||''))]);}
export async function saveCategory(c:Category){await database().prepare('INSERT INTO categories (id,name,image,icon,position,hidden) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,image=excluded.image,icon=excluded.icon,position=excluded.position,hidden=excluded.hidden').bind(c.id,c.name,c.image,c.icon,c.position,+c.hidden).run();}
export async function saveMarket(m:Market){const db=database();await db.batch([db.prepare('INSERT INTO markets (id,name,date,status,data) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,date=excluded.date,status=excluded.status,data=excluded.data').bind(m.id,m.name,m.date,m.status,JSON.stringify({...m,products:[],deals:[]})),db.prepare('DELETE FROM market_products WHERE market_id=?').bind(m.id),db.prepare('DELETE FROM market_deals WHERE market_id=?').bind(m.id),...m.products.map(id=>db.prepare('INSERT INTO market_products (market_id,product_id) VALUES (?,?)').bind(m.id,id)),...m.deals.filter(Boolean).map(label=>db.prepare('INSERT INTO market_deals (id,market_id,label) VALUES (?,?,?)').bind(crypto.randomUUID(),m.id,label))]);}
export async function saveSettings(s:Settings){await database().prepare('UPDATE site_settings SET data=? WHERE id=?').bind(JSON.stringify(s),'main').run();}
