import {z} from 'zod';
const text=z.string().max(10000),short=z.string().max(300),id=z.string().min(1).max(100);
const url=z.string().max(2000).refine(v=>!v||v.startsWith('/api/media/')||v.startsWith('/images/')||/^https:\/\//.test(v),'Use an HTTPS URL');
export const photo=z.object({id:id.optional(),mediaId:id.optional(),url,alt:short});
export const productSchema=z.object({id,slug:z.string().min(1).max(150).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:short.min(1),categoryId:id,price:z.number().min(0).max(100000),salePrice:z.number().min(0).optional(),bundlePrice:z.number().min(0).optional(),bundleQuantity:z.number().int().min(1).optional(),bundleLabel:short.optional(),shortDescription:short,description:text,subcategory:short,tags:z.array(short).max(30),type:z.enum(['Fidget','Creature','Dragon','Keyring','Collectible','Desk Toy','Puzzle','Custom','Gift']),size:short,age:z.enum(['3+','5+','8+','Teens','Adults']),material:short,care:text,safety:text,makerNote:text,customisable:z.boolean(),stock:z.enum(['In Stock','Low Stock','Sold Out','Made to Order']),marketAvailable:z.boolean(),featured:z.boolean(),isNew:z.boolean(),marketPick:z.boolean(),published:z.boolean(),archived:z.boolean(),photos:z.array(photo).max(20),colours:z.array(z.object({name:short.min(1),hex:z.string().regex(/^$|^#[0-9a-fA-F]{6}$/),photo:url.optional()})).max(30),video:url,occasions:z.array(short).max(10),related:z.array(id).max(20),createdAt:short,updatedAt:short}).refine(p=>p.salePrice===undefined||p.salePrice<=p.price,'Sale price must not exceed regular price');
export const categorySchema=z.object({id,name:short.min(1),image:url,icon:short,position:z.number().int().min(0),hidden:z.boolean()});
export const marketSchema=z.object({id,name:short.min(1),date:z.string().regex(/^$|^\d{4}-\d{2}-\d{2}$/),status:z.enum(['Pending','Confirmed','Completed','Cancelled']),start:z.string().regex(/^$|^\d{2}:\d{2}$/),end:z.string().regex(/^$|^\d{2}:\d{2}$/),venue:short,address:short,stall:short,notes:text,photos:z.array(photo).max(20),products:z.array(id).max(1000),deals:z.array(short).max(30)}).refine(m=>m.status!=='Confirmed'||!!(m.date&&m.start&&m.end),'Confirmed markets need a date and start/end times').refine(m=>!m.start||!m.end||m.end>m.start,'End time must follow start time');
export const settingsSchema=z.object({businessName:short.min(1),tagline:short,email:z.union([z.literal(''),z.string().email()]),instagram:url,tiktok:url,youtube:url,location:short,announcement:short,marketBanner:short,about:text,maker:text,reviews:text,transport:text});
export const enquirySchema=z.object({kind:z.enum(['contact','custom','reservation']),name:short.min(2),email:z.string().email().max(254),subject:short.optional(),message:z.string().min(10).max(5000),productId:id.optional(),colour:short.optional(),quantity:z.number().int().min(1).max(100).optional(),marketId:id.optional(),productType:short.optional(),size:short.optional(),neededBy:short.optional(),reference:short.optional(),website:z.string().max(100).optional()});
